# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/calculationsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_metricsWindow(object):
    def setupUi(self, metricsWindow):
        metricsWindow.setObjectName("metricsWindow")
        metricsWindow.setFixedSize(846, 725)
        metricsWindow.setStyleSheet("background-color:#224562;")
        self.projectNameLbl_2 = QtWidgets.QLabel(metricsWindow)
        self.projectNameLbl_2.setGeometry(QtCore.QRect(40, 30, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.projectNameLbl_2.setFont(font)
        self.projectNameLbl_2.setStyleSheet("color: #FFD43B;")
        self.projectNameLbl_2.setObjectName("projectNameLbl_2")
        self.nocLbl = QtWidgets.QLabel(metricsWindow)
        self.nocLbl.setGeometry(QtCore.QRect(600, 50, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.nocLbl.setFont(font)
        self.nocLbl.setStyleSheet("color: #FFD43B;")
        self.nocLbl.setObjectName("nocLbl")
        self.exportExcelBtn = QtWidgets.QPushButton(metricsWindow)
        self.exportExcelBtn.setGeometry(QtCore.QRect(430, 650, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exportExcelBtn.setFont(font)
        self.exportExcelBtn.setStyleSheet("color:white;\n"
                                          "font-weight: bold;\n"
                                          "background-color: #00A300;")
        self.exportExcelBtn.setObjectName("exportExcelBtn")
        self.helpBtn = QtWidgets.QPushButton(metricsWindow)
        self.helpBtn.setGeometry(QtCore.QRect(800, 680, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.helpBtn.setFont(font)
        self.helpBtn.setStyleSheet("color:white;\n"
                                   "font-weight: bold;\n"
                                   "background-color: #B68F05;")
        self.helpBtn.setObjectName("helpBtn")
        self.backMainBtn = QtWidgets.QPushButton(metricsWindow)
        self.backMainBtn.setGeometry(QtCore.QRect(140, 650, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.backMainBtn.setFont(font)
        self.backMainBtn.setStyleSheet("color:white;\n"
                                       "font-weight: bold;\n"
                                       "background-color: #B68F05;;")
        self.backMainBtn.setObjectName("backMainBtn")
        self.metricsTbl = QtWidgets.QTableWidget(metricsWindow)
        self.metricsTbl.setGeometry(QtCore.QRect(30, 80, 791, 541))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.metricsTbl.setFont(font)
        self.metricsTbl.setStyleSheet("background-color:white;")
        self.metricsTbl.setShowGrid(True)
        self.metricsTbl.setGridStyle(QtCore.Qt.DashLine)
        self.metricsTbl.setRowCount(15)
        self.metricsTbl.setColumnCount(10)
        self.metricsTbl.setObjectName("metricsTbl")
        item = QtWidgets.QTableWidgetItem()
        self.metricsTbl.setItem(0, 0, item)
        self.metricsTbl.verticalHeader().setMinimumSectionSize(23)

        self.retranslateUi(metricsWindow)
        QtCore.QMetaObject.connectSlotsByName(metricsWindow)

    def retranslateUi(self, metricsWindow):
        _translate = QtCore.QCoreApplication.translate
        metricsWindow.setWindowTitle(_translate("metricsWindow", "Dialog"))
        self.projectNameLbl_2.setText(_translate("metricsWindow", "Metrics for {{Project_name}}"))
        self.nocLbl.setText(_translate("metricsWindow", "Classes Found (NOC Metric) = {{Number}}"))
        self.exportExcelBtn.setText(_translate("metricsWindow", "Export Results to Excel File"))
        self.helpBtn.setText(_translate("metricsWindow", "?"))
        self.backMainBtn.setText(_translate("metricsWindow", "Back to main screen"))
        self.metricsTbl.setSortingEnabled(False)
        __sortingEnabled = self.metricsTbl.isSortingEnabled()
        self.metricsTbl.setSortingEnabled(False)
        item = self.metricsTbl.item(0, 0)
        item.setText(_translate("metricsWindow", "Test"))
        self.metricsTbl.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    metricsWindow = QtWidgets.QDialog()
    ui = Ui_metricsWindow()
    ui.setupUi(metricsWindow)
    metricsWindow.show()
    sys.exit(app.exec_())
